# Generated by Django 2.1 on 2018-08-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20180819_2211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLogin',
            new_name='UsersLogin',
        ),
    ]
